import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Geist Sans font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Optional: Improves font loading performance
});

// Load Geist Mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // Optional: Improves font loading performance
});

export const metadata = {
  title: "Project Dashboard MSL",
  description: "Generated by create next app",
  icons: {
    icon: "/mslDB.png", // Updated to absolute path from public directory
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}